# Generated by Django 5.2.5 on 2025-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('matric_number', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('project_role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('github', models.URLField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
            ],
        ),
    ]
