# Generated by Django 5.2.7 on 2025-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
