# Generated by Django 5.2.5 on 2025-08-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_department_alter_allowedmatric_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matric_number',
            field=models.CharField(max_length=50),
        ),
    ]
