# Generated by Django 5.2.5 on 2025-08-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_department_alter_profile_matric_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedmatric',
            options={'verbose_name': 'Allowed Matric', 'verbose_name_plural': 'Allowed Matrics'},
        ),
        migrations.AddField(
            model_name='allowedmatric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='allowedmatric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='allowedmatric',
            name='matric_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matric_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
