# Generated by Django 5.2.7 on 2025-10-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_team_member',
            field=models.BooleanField(default=False),
        ),
    ]
